; -------- Measures -------

[MeasureAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
FFTSize=#FFTSize#
FFTOverlap=(#FFTSize#/2)
FFTAttack=#FFTAttack#
FFTDecay=#FFTDecay#
Bands=90
FreqMin=#FreqMin#
FreqMax=#FreqMax#
Sensitivity=#Sensitivity#
Group=MusicTab|Spectrum


;#program in Python to print out measures
; measure = "[MeasureBand#]\n"
; measure += "Measure=Plugin\n"
; measure += "Plugin=AudioLevel\n"
; measure += "Parent=MeasureAudio\n"
; measure += "Type=Band\n"
; measure += "BandIdx=#\n"
; measure += "Group=MusicTab|Spectrum\n\n"
; for i in range(90):
    ; print(measure.replace("#", str(i)))


[MeasureBand1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1
Group=MusicTab|Spectrum

[MeasureBand2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2
Group=MusicTab|Spectrum

[MeasureBand3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3
Group=MusicTab|Spectrum

[MeasureBand4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4
Group=MusicTab|Spectrum

[MeasureBand5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5
Group=MusicTab|Spectrum

[MeasureBand6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6
Group=MusicTab|Spectrum

[MeasureBand7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7
Group=MusicTab|Spectrum

[MeasureBand8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8
Group=MusicTab|Spectrum

[MeasureBand9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9
Group=MusicTab|Spectrum

[MeasureBand10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10
Group=MusicTab|Spectrum

[MeasureBand11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11
Group=MusicTab|Spectrum

[MeasureBand12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12
Group=MusicTab|Spectrum

[MeasureBand13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13
Group=MusicTab|Spectrum

[MeasureBand14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14
Group=MusicTab|Spectrum

[MeasureBand15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15
Group=MusicTab|Spectrum

[MeasureBand16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16
Group=MusicTab|Spectrum

[MeasureBand17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17
Group=MusicTab|Spectrum

[MeasureBand18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18
Group=MusicTab|Spectrum

[MeasureBand19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19
Group=MusicTab|Spectrum

[MeasureBand20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20
Group=MusicTab|Spectrum

[MeasureBand21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21
Group=MusicTab|Spectrum

[MeasureBand22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22
Group=MusicTab|Spectrum

[MeasureBand23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23
Group=MusicTab|Spectrum

[MeasureBand24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24
Group=MusicTab|Spectrum

[MeasureBand25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25
Group=MusicTab|Spectrum

[MeasureBand26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26
Group=MusicTab|Spectrum

[MeasureBand27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27
Group=MusicTab|Spectrum

[MeasureBand28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28
Group=MusicTab|Spectrum

[MeasureBand29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29
Group=MusicTab|Spectrum

[MeasureBand30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30
Group=MusicTab|Spectrum

[MeasureBand31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31
Group=MusicTab|Spectrum

[MeasureBand32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32
Group=MusicTab|Spectrum

[MeasureBand33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33
Group=MusicTab|Spectrum

[MeasureBand34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34
Group=MusicTab|Spectrum

[MeasureBand35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35
Group=MusicTab|Spectrum

[MeasureBand36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36
Group=MusicTab|Spectrum

[MeasureBand37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37
Group=MusicTab|Spectrum

[MeasureBand38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38
Group=MusicTab|Spectrum

[MeasureBand39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39
Group=MusicTab|Spectrum

[MeasureBand40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40
Group=MusicTab|Spectrum

[MeasureBand41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41
Group=MusicTab|Spectrum

[MeasureBand42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42
Group=MusicTab|Spectrum

[MeasureBand43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43
Group=MusicTab|Spectrum

[MeasureBand44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44
Group=MusicTab|Spectrum

[MeasureBand45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45
Group=MusicTab|Spectrum

[MeasureBand46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46
Group=MusicTab|Spectrum

[MeasureBand47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47
Group=MusicTab|Spectrum

[MeasureBand48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48
Group=MusicTab|Spectrum

[MeasureBand49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49
Group=MusicTab|Spectrum

[MeasureBand50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50
Group=MusicTab|Spectrum

[MeasureBand51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51
Group=MusicTab|Spectrum

[MeasureBand52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52
Group=MusicTab|Spectrum

[MeasureBand53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53
Group=MusicTab|Spectrum

[MeasureBand54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54
Group=MusicTab|Spectrum

[MeasureBand55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55
Group=MusicTab|Spectrum

[MeasureBand56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56
Group=MusicTab|Spectrum

[MeasureBand57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57
Group=MusicTab|Spectrum

[MeasureBand58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58
Group=MusicTab|Spectrum

[MeasureBand59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59
Group=MusicTab|Spectrum

[MeasureBand60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60
Group=MusicTab|Spectrum

[MeasureBand61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61
Group=MusicTab|Spectrum

[MeasureBand62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62
Group=MusicTab|Spectrum

[MeasureBand63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63
Group=MusicTab|Spectrum

[MeasureBand64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64
Group=MusicTab|Spectrum

[MeasureBand65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65
Group=MusicTab|Spectrum

[MeasureBand66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66
Group=MusicTab|Spectrum

[MeasureBand67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67
Group=MusicTab|Spectrum

[MeasureBand68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68
Group=MusicTab|Spectrum

[MeasureBand69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69
Group=MusicTab|Spectrum

[MeasureBand70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70
Group=MusicTab|Spectrum

[MeasureBand71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71
Group=MusicTab|Spectrum

[MeasureBand72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72
Group=MusicTab|Spectrum

[MeasureBand73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73
Group=MusicTab|Spectrum

[MeasureBand74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74
Group=MusicTab|Spectrum

[MeasureBand75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75
Group=MusicTab|Spectrum

[MeasureBand76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76
Group=MusicTab|Spectrum

[MeasureBand77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77
Group=MusicTab|Spectrum

[MeasureBand78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78
Group=MusicTab|Spectrum

[MeasureBand79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79
Group=MusicTab|Spectrum

[MeasureBand80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80
Group=MusicTab|Spectrum

[MeasureBand81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81
Group=MusicTab|Spectrum

[MeasureBand82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82
Group=MusicTab|Spectrum

[MeasureBand83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83
Group=MusicTab|Spectrum

[MeasureBand84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84
Group=MusicTab|Spectrum

[MeasureBand85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85
Group=MusicTab|Spectrum

[MeasureBand86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86
Group=MusicTab|Spectrum

[MeasureBand87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87
Group=MusicTab|Spectrum

[MeasureBand88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88
Group=MusicTab|Spectrum

[MeasureBand89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89
Group=MusicTab|Spectrum

; ------ Meters --------
[Variables]
MatrixN30=(cos(Rad(-30)));(-sin(Rad(-30)));(sin(Rad(-30)));(cos(Rad(-30)));0;0
MatrixN90=(cos(Rad(-90)));(-sin(Rad(-90)));(sin(Rad(-90)));(cos(Rad(-90)));0;0
MatrixN150=(cos(Rad(-150)));(-sin(Rad(-150)));(sin(Rad(-150)));(cos(Rad(-150)));0;0
Matrix150=(cos(Rad(150)));(-sin(Rad(150)));(sin(Rad(150)));(cos(Rad(150)));0;0
Matrix90=(cos(Rad(90)));(-sin(Rad(90)));(sin(Rad(90)));(cos(Rad(90)));0;0
Matrix30=(cos(Rad(30)));(-sin(Rad(30)));(sin(Rad(30)));(cos(Rad(30)));0;0
; MeterTypeSpectrum=Image
MeterTypeSpectrum=Bar

[MeterSpectrumStyle]
BarImage=#@#images\spectrumBar.png
BarOrientation=Vertical
; ImageName=#@#images\spectrumBar.png
; Group=MusicTab|MediaPlayer
X=5R
Y=r
 
 
 ; #program in Python
; meter = "[MeterSpectrumA%]\n"
; meter += "Meter=#MeterTypeSpectrum#\n"
; meter += "MeterStyle=MeterSpectrumStyle\n"
; meter += "MeasureName=MeasureBand$\n"
; meter += "TransformationMatrix=#MatrixN30#\n"

; for i in range(2, 28):
    ; print(meter.replace("%", str(i)).replace("$", str(i+29)))
 
 ;--------- Section A ------------
[MeterSpectrumA1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand30
TransformationMatrix=#MatrixN30#
X=450
Y=-150

[MeterSpectrumA2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand31
TransformationMatrix=#MatrixN30#

[MeterSpectrumA3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand32
TransformationMatrix=#MatrixN30#

[MeterSpectrumA4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand33
TransformationMatrix=#MatrixN30#

[MeterSpectrumA5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand34
TransformationMatrix=#MatrixN30#

[MeterSpectrumA6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand35
TransformationMatrix=#MatrixN30#

[MeterSpectrumA7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand36
TransformationMatrix=#MatrixN30#

[MeterSpectrumA8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand37
TransformationMatrix=#MatrixN30#

[MeterSpectrumA9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand38
TransformationMatrix=#MatrixN30#

[MeterSpectrumA10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand39
TransformationMatrix=#MatrixN30#

[MeterSpectrumA11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand40
TransformationMatrix=#MatrixN30#

[MeterSpectrumA12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand41
TransformationMatrix=#MatrixN30#

[MeterSpectrumA13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand42
TransformationMatrix=#MatrixN30#

[MeterSpectrumA14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand43
TransformationMatrix=#MatrixN30#

[MeterSpectrumA15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand44
TransformationMatrix=#MatrixN30#

[MeterSpectrumA16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand45
TransformationMatrix=#MatrixN30#

[MeterSpectrumA17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand46
TransformationMatrix=#MatrixN30#

[MeterSpectrumA18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand47
TransformationMatrix=#MatrixN30#

[MeterSpectrumA19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand48
TransformationMatrix=#MatrixN30#

[MeterSpectrumA20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand49
TransformationMatrix=#MatrixN30#

[MeterSpectrumA21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand50
TransformationMatrix=#MatrixN30#

[MeterSpectrumA22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand51
TransformationMatrix=#MatrixN30#

[MeterSpectrumA23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand52
TransformationMatrix=#MatrixN30#

[MeterSpectrumA24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand53
TransformationMatrix=#MatrixN30#

[MeterSpectrumA25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand54
TransformationMatrix=#MatrixN30#

[MeterSpectrumA26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand55
TransformationMatrix=#MatrixN30#

[MeterSpectrumA27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand56
TransformationMatrix=#MatrixN30#


 ;--------- Section B ------------
[MeterSpectrumB1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand3
TransformationMatrix=#MatrixN90#
X=340
Y=-750

[MeterSpectrumB2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand4
TransformationMatrix=#MatrixN90#

[MeterSpectrumB3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand5
TransformationMatrix=#MatrixN90#

[MeterSpectrumB4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand6
TransformationMatrix=#MatrixN90#

[MeterSpectrumB5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand7
TransformationMatrix=#MatrixN90#

[MeterSpectrumB6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand8
TransformationMatrix=#MatrixN90#

[MeterSpectrumB7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand9
TransformationMatrix=#MatrixN90#

[MeterSpectrumB8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand10
TransformationMatrix=#MatrixN90#

[MeterSpectrumB9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand11
TransformationMatrix=#MatrixN90#

[MeterSpectrumB10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand12
TransformationMatrix=#MatrixN90#

[MeterSpectrumB11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand13
TransformationMatrix=#MatrixN90#

[MeterSpectrumB12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand14
TransformationMatrix=#MatrixN90#

[MeterSpectrumB13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand15
TransformationMatrix=#MatrixN90#

[MeterSpectrumB14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand16
TransformationMatrix=#MatrixN90#

[MeterSpectrumB15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand17
TransformationMatrix=#MatrixN90#

[MeterSpectrumB16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand18
TransformationMatrix=#MatrixN90#

[MeterSpectrumB17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand19
TransformationMatrix=#MatrixN90#

[MeterSpectrumB18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand20
TransformationMatrix=#MatrixN90#

[MeterSpectrumB19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand21
TransformationMatrix=#MatrixN90#

[MeterSpectrumB20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand22
TransformationMatrix=#MatrixN90#

[MeterSpectrumB21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand23
TransformationMatrix=#MatrixN90#

[MeterSpectrumB22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand24
TransformationMatrix=#MatrixN90#

[MeterSpectrumB23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand25
TransformationMatrix=#MatrixN90#

[MeterSpectrumB24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand26
TransformationMatrix=#MatrixN90#

[MeterSpectrumB25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand27
TransformationMatrix=#MatrixN90#

[MeterSpectrumB26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand28
TransformationMatrix=#MatrixN90#

[MeterSpectrumB27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand29
TransformationMatrix=#MatrixN90#

 ;--------- Section C ------------
[MeterSpectrumC1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand60
TransformationMatrix=#MatrixN150#
X=-240
Y=-960

[MeterSpectrumC2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand61
TransformationMatrix=#MatrixN150#

[MeterSpectrumC3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand62
TransformationMatrix=#MatrixN150#

[MeterSpectrumC4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand63
TransformationMatrix=#MatrixN150#

[MeterSpectrumC5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand64
TransformationMatrix=#MatrixN150#

[MeterSpectrumC6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand65
TransformationMatrix=#MatrixN150#

[MeterSpectrumC7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand66
TransformationMatrix=#MatrixN150#

[MeterSpectrumC8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand67
TransformationMatrix=#MatrixN150#

[MeterSpectrumC9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand68
TransformationMatrix=#MatrixN150#

[MeterSpectrumC10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand69
TransformationMatrix=#MatrixN150#

[MeterSpectrumC11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand70
TransformationMatrix=#MatrixN150#

[MeterSpectrumC12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand71
TransformationMatrix=#MatrixN150#

[MeterSpectrumC13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand72
TransformationMatrix=#MatrixN150#

[MeterSpectrumC14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand73
TransformationMatrix=#MatrixN150#

[MeterSpectrumC15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand74
TransformationMatrix=#MatrixN150#

[MeterSpectrumC16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand75
TransformationMatrix=#MatrixN150#

[MeterSpectrumC17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand76
TransformationMatrix=#MatrixN150#

[MeterSpectrumC18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand77
TransformationMatrix=#MatrixN150#

[MeterSpectrumC19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand78
TransformationMatrix=#MatrixN150#

[MeterSpectrumC20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand79
TransformationMatrix=#MatrixN150#

[MeterSpectrumC21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand80
TransformationMatrix=#MatrixN150#

[MeterSpectrumC22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand81
TransformationMatrix=#MatrixN150#

[MeterSpectrumC23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand82
TransformationMatrix=#MatrixN150#

[MeterSpectrumC24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand83
TransformationMatrix=#MatrixN150#

[MeterSpectrumC25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand84
TransformationMatrix=#MatrixN150#

[MeterSpectrumC26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand85
TransformationMatrix=#MatrixN150#

[MeterSpectrumC27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand86
TransformationMatrix=#MatrixN150#

 ;--------- Section D ------------
[MeterSpectrumD1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand86
TransformationMatrix=#Matrix150#
X=-710
Y=-560

[MeterSpectrumD2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand85
TransformationMatrix=#Matrix150#

[MeterSpectrumD3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand84
TransformationMatrix=#Matrix150#

[MeterSpectrumD4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand83
TransformationMatrix=#Matrix150#

[MeterSpectrumD5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand82
TransformationMatrix=#Matrix150#

[MeterSpectrumD6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand81
TransformationMatrix=#Matrix150#

[MeterSpectrumD7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand80
TransformationMatrix=#Matrix150#

[MeterSpectrumD8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand79
TransformationMatrix=#Matrix150#

[MeterSpectrumD9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand78
TransformationMatrix=#Matrix150#

[MeterSpectrumD10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand77
TransformationMatrix=#Matrix150#

[MeterSpectrumD11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand76
TransformationMatrix=#Matrix150#

[MeterSpectrumD12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand75
TransformationMatrix=#Matrix150#

[MeterSpectrumD13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand74
TransformationMatrix=#Matrix150#

[MeterSpectrumD14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand73
TransformationMatrix=#Matrix150#

[MeterSpectrumD15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand72
TransformationMatrix=#Matrix150#

[MeterSpectrumD16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand71
TransformationMatrix=#Matrix150#

[MeterSpectrumD17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand70
TransformationMatrix=#Matrix150#

[MeterSpectrumD18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand69
TransformationMatrix=#Matrix150#

[MeterSpectrumD19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand68
TransformationMatrix=#Matrix150#

[MeterSpectrumD20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand67
TransformationMatrix=#Matrix150#

[MeterSpectrumD21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand66
TransformationMatrix=#Matrix150#

[MeterSpectrumD22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand65
TransformationMatrix=#Matrix150#

[MeterSpectrumD23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand64
TransformationMatrix=#Matrix150#

[MeterSpectrumD24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand63
TransformationMatrix=#Matrix150#

[MeterSpectrumD25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand62
TransformationMatrix=#Matrix150#

[MeterSpectrumD26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand61
TransformationMatrix=#Matrix150#

[MeterSpectrumD27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand60
TransformationMatrix=#Matrix150#

 ;--------- Section E ------------
[MeterSpectrumE1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand29
TransformationMatrix=#Matrix90#
X=-600
Y=40

[MeterSpectrumE2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand28
TransformationMatrix=#Matrix90#

[MeterSpectrumE3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand27
TransformationMatrix=#Matrix90#

[MeterSpectrumE4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand26
TransformationMatrix=#Matrix90#

[MeterSpectrumE5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand25
TransformationMatrix=#Matrix90#

[MeterSpectrumE6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand24
TransformationMatrix=#Matrix90#

[MeterSpectrumE7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand23
TransformationMatrix=#Matrix90#

[MeterSpectrumE8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand22
TransformationMatrix=#Matrix90#

[MeterSpectrumE9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand21
TransformationMatrix=#Matrix90#

[MeterSpectrumE10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand20
TransformationMatrix=#Matrix90#

[MeterSpectrumE11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand19
TransformationMatrix=#Matrix90#

[MeterSpectrumE12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand18
TransformationMatrix=#Matrix90#

[MeterSpectrumE13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand17
TransformationMatrix=#Matrix90#

[MeterSpectrumE14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand16
TransformationMatrix=#Matrix90#

[MeterSpectrumE15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand15
TransformationMatrix=#Matrix90#

[MeterSpectrumE16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand14
TransformationMatrix=#Matrix90#

[MeterSpectrumE17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand13
TransformationMatrix=#Matrix90#

[MeterSpectrumE18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand12
TransformationMatrix=#Matrix90#

[MeterSpectrumE19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand11
TransformationMatrix=#Matrix90#

[MeterSpectrumE20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand10
TransformationMatrix=#Matrix90#

[MeterSpectrumE21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand9
TransformationMatrix=#Matrix90#

[MeterSpectrumE22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand8
TransformationMatrix=#Matrix90#

[MeterSpectrumE23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand7
TransformationMatrix=#Matrix90#

[MeterSpectrumE24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand6
TransformationMatrix=#Matrix90#

[MeterSpectrumE25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand5
TransformationMatrix=#Matrix90#

[MeterSpectrumE26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand4
TransformationMatrix=#Matrix90#

[MeterSpectrumE27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand3
TransformationMatrix=#Matrix90#

 ;--------- Section F ------------
[MeterSpectrumF1]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand56
TransformationMatrix=#Matrix30#
X=-20
Y=250

[MeterSpectrumF2]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand55
TransformationMatrix=#Matrix30#

[MeterSpectrumF3]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand54
TransformationMatrix=#Matrix30#

[MeterSpectrumF4]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand53
TransformationMatrix=#Matrix30#

[MeterSpectrumF5]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand52
TransformationMatrix=#Matrix30#

[MeterSpectrumF6]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand51
TransformationMatrix=#Matrix30#

[MeterSpectrumF7]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand50
TransformationMatrix=#Matrix30#

[MeterSpectrumF8]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand49
TransformationMatrix=#Matrix30#

[MeterSpectrumF9]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand48
TransformationMatrix=#Matrix30#

[MeterSpectrumF10]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand47
TransformationMatrix=#Matrix30#

[MeterSpectrumF11]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand46
TransformationMatrix=#Matrix30#

[MeterSpectrumF12]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand45
TransformationMatrix=#Matrix30#

[MeterSpectrumF13]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand44
TransformationMatrix=#Matrix30#

[MeterSpectrumF14]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand43
TransformationMatrix=#Matrix30#

[MeterSpectrumF15]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand42
TransformationMatrix=#Matrix30#

[MeterSpectrumF16]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand41
TransformationMatrix=#Matrix30#

[MeterSpectrumF17]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand40
TransformationMatrix=#Matrix30#

[MeterSpectrumF18]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand39
TransformationMatrix=#Matrix30#

[MeterSpectrumF19]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand38
TransformationMatrix=#Matrix30#

[MeterSpectrumF20]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand37
TransformationMatrix=#Matrix30#

[MeterSpectrumF21]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand36
TransformationMatrix=#Matrix30#

[MeterSpectrumF22]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand35
TransformationMatrix=#Matrix30#

[MeterSpectrumF23]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand34
TransformationMatrix=#Matrix30#

[MeterSpectrumF24]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand33
TransformationMatrix=#Matrix30#

[MeterSpectrumF25]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand32
TransformationMatrix=#Matrix30#

[MeterSpectrumF26]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand31
TransformationMatrix=#Matrix30#

[MeterSpectrumF27]
Meter=#MeterTypeSpectrum#
MeterStyle=MeterSpectrumStyle
MeasureName=MeasureBand30
TransformationMatrix=#Matrix30#